apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

kubernetesVersion: "1.26"

managedNodeGroups:
  - name: spot
    instanceType: m5.large
    desiredCapacity: 1
    spot: true
